<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="15" ignored="0" total="40" passed="25">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="302118" started-at="2021-10-17T13:03:43 IST" finished-at="2021-10-17T13:08:45 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="302118" started-at="2021-10-17T13:03:43 IST" finished-at="2021-10-17T13:08:45 IST">
      <class name="com.plp.tests.ProductPageValidation">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="beforeClass" is-config="true" duration-ms="80154" started-at="2021-10-17T13:03:43 IST" finished-at="2021-10-17T13:05:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="CartAddDate()[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="CartAddDate" duration-ms="30890" started-at="2021-10-17T13:05:03 IST" finished-at="2021-10-17T13:05:34 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Website is accepting previous delivery date]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Website is accepting previous delivery date
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.CartAddDate(ProductPageValidation.java:161)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CartAddDate -->
        <test-method status="PASS" signature="ProductNavigation(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ProductNavigation" duration-ms="8993" started-at="2021-10-17T13:05:39 IST" data-provider="productnavigation" finished-at="2021-10-17T13:05:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[HP LP3065]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductNavigation -->
        <test-method status="PASS" signature="ProductNavigation(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ProductNavigation" duration-ms="6576" started-at="2021-10-17T13:05:48 IST" data-provider="productnavigation" finished-at="2021-10-17T13:05:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[iMac]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductNavigation -->
        <test-method status="PASS" signature="ProductNavigation(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ProductNavigation" duration-ms="3694" started-at="2021-10-17T13:05:54 IST" data-provider="productnavigation" finished-at="2021-10-17T13:05:58 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductNavigation -->
        <test-method status="PASS" signature="ProductNavigation(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ProductNavigation" duration-ms="3797" started-at="2021-10-17T13:05:58 IST" data-provider="productnavigation" finished-at="2021-10-17T13:06:02 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook Air]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductNavigation -->
        <test-method status="FAIL" signature="ProductNavigation(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ProductNavigation" duration-ms="5290" started-at="2021-10-17T13:06:02 IST" data-provider="productnavigation" finished-at="2021-10-17T13:06:07 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Canon EOS 5D]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [sdf] but found [Canon EOS 5D]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [sdf] but found [Canon EOS 5D]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.plp.tests.ProductPageValidation.ProductNavigation(ProductPageValidation.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductNavigation -->
        <test-method status="PASS" signature="ProductNavigation(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ProductNavigation" duration-ms="4200" started-at="2021-10-17T13:06:07 IST" data-provider="productnavigation" finished-at="2021-10-17T13:06:11 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Samsung Galaxy Tab 10.1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductNavigation -->
        <test-method status="PASS" signature="ReviewFunc(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ReviewFunc" duration-ms="6630" started-at="2021-10-17T13:06:11 IST" data-provider="productnavigation" finished-at="2021-10-17T13:06:18 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[HP LP3065]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReviewFunc -->
        <test-method status="PASS" signature="ReviewFunc(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ReviewFunc" duration-ms="6320" started-at="2021-10-17T13:06:18 IST" data-provider="productnavigation" finished-at="2021-10-17T13:06:24 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[iMac]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReviewFunc -->
        <test-method status="PASS" signature="ReviewFunc(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ReviewFunc" duration-ms="5123" started-at="2021-10-17T13:06:24 IST" data-provider="productnavigation" finished-at="2021-10-17T13:06:29 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReviewFunc -->
        <test-method status="PASS" signature="ReviewFunc(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ReviewFunc" duration-ms="5225" started-at="2021-10-17T13:06:29 IST" data-provider="productnavigation" finished-at="2021-10-17T13:06:35 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook Air]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReviewFunc -->
        <test-method status="PASS" signature="ReviewFunc(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ReviewFunc" duration-ms="5847" started-at="2021-10-17T13:06:35 IST" data-provider="productnavigation" finished-at="2021-10-17T13:06:41 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Canon EOS 5D]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReviewFunc -->
        <test-method status="PASS" signature="ReviewFunc(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="ReviewFunc" duration-ms="6752" started-at="2021-10-17T13:06:41 IST" data-provider="productnavigation" finished-at="2021-10-17T13:06:47 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Samsung Galaxy Tab 10.1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReviewFunc -->
        <test-method status="PASS" signature="VerifyAddToCart(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyAddToCart" duration-ms="5169" started-at="2021-10-17T13:06:47 IST" data-provider="productnavigation" finished-at="2021-10-17T13:06:53 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[HP LP3065]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAddToCart -->
        <test-method status="PASS" signature="VerifyAddToCart(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyAddToCart" duration-ms="8937" started-at="2021-10-17T13:06:53 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:01 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[iMac]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAddToCart -->
        <test-method status="PASS" signature="VerifyAddToCart(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyAddToCart" duration-ms="4402" started-at="2021-10-17T13:07:01 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:06 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAddToCart -->
        <test-method status="PASS" signature="VerifyAddToCart(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyAddToCart" duration-ms="4601" started-at="2021-10-17T13:07:06 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:10 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook Air]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAddToCart -->
        <test-method status="FAIL" signature="VerifyAddToCart(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyAddToCart" duration-ms="6692" started-at="2021-10-17T13:07:10 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Canon EOS 5D]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Product is not added to the cart]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Product is not added to the cart
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.VerifyAddToCart(ProductPageValidation.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAddToCart -->
        <test-method status="PASS" signature="VerifyAddToCart(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyAddToCart" duration-ms="4442" started-at="2021-10-17T13:07:17 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:22 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Samsung Galaxy Tab 10.1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAddToCart -->
        <test-method status="FAIL" signature="VerifyFields()[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyFields" duration-ms="5103" started-at="2021-10-17T13:07:22 IST" finished-at="2021-10-17T13:07:27 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[First Name Field is Accepting Numeric Data]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: First Name Field is Accepting Numeric Data
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.VerifyFields(ProductPageValidation.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyFields -->
        <test-method status="FAIL" signature="VerifyReviews(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyReviews" duration-ms="3988" started-at="2021-10-17T13:07:27 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:31 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[HP LP3065]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Reviews are not available]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Reviews are not available
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.VerifyReviews(ProductPageValidation.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyReviews -->
        <test-method status="FAIL" signature="VerifyReviews(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyReviews" duration-ms="4545" started-at="2021-10-17T13:07:31 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:35 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[iMac]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Reviews are not available]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Reviews are not available
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.VerifyReviews(ProductPageValidation.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyReviews -->
        <test-method status="FAIL" signature="VerifyReviews(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyReviews" duration-ms="3769" started-at="2021-10-17T13:07:35 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:39 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Reviews are not available]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Reviews are not available
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.VerifyReviews(ProductPageValidation.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyReviews -->
        <test-method status="FAIL" signature="VerifyReviews(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyReviews" duration-ms="3790" started-at="2021-10-17T13:07:39 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:43 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook Air]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Reviews are not available]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Reviews are not available
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.VerifyReviews(ProductPageValidation.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyReviews -->
        <test-method status="FAIL" signature="VerifyReviews(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyReviews" duration-ms="3837" started-at="2021-10-17T13:07:43 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:47 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Canon EOS 5D]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Reviews are not available]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Reviews are not available
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.VerifyReviews(ProductPageValidation.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyReviews -->
        <test-method status="FAIL" signature="VerifyReviews(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="VerifyReviews" duration-ms="4002" started-at="2021-10-17T13:07:47 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:51 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Samsung Galaxy Tab 10.1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Reviews are not available]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Reviews are not available
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.VerifyReviews(ProductPageValidation.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyReviews -->
        <test-method status="PASS" signature="verifyDescription(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifyDescription" duration-ms="3313" started-at="2021-10-17T13:07:51 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:54 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[HP LP3065]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDescription -->
        <test-method status="PASS" signature="verifyDescription(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifyDescription" duration-ms="3641" started-at="2021-10-17T13:07:54 IST" data-provider="productnavigation" finished-at="2021-10-17T13:07:58 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[iMac]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDescription -->
        <test-method status="PASS" signature="verifyDescription(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifyDescription" duration-ms="3271" started-at="2021-10-17T13:07:58 IST" data-provider="productnavigation" finished-at="2021-10-17T13:08:01 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDescription -->
        <test-method status="PASS" signature="verifyDescription(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifyDescription" duration-ms="3557" started-at="2021-10-17T13:08:01 IST" data-provider="productnavigation" finished-at="2021-10-17T13:08:05 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook Air]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDescription -->
        <test-method status="PASS" signature="verifyDescription(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifyDescription" duration-ms="3436" started-at="2021-10-17T13:08:05 IST" data-provider="productnavigation" finished-at="2021-10-17T13:08:08 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Canon EOS 5D]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDescription -->
        <test-method status="PASS" signature="verifyDescription(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifyDescription" duration-ms="3494" started-at="2021-10-17T13:08:08 IST" data-provider="productnavigation" finished-at="2021-10-17T13:08:11 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Samsung Galaxy Tab 10.1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDescription -->
        <test-method status="PASS" signature="verifyMandatoryFields()[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifyMandatoryFields" duration-ms="3817" started-at="2021-10-17T13:08:11 IST" finished-at="2021-10-17T13:08:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMandatoryFields -->
        <test-method status="FAIL" signature="verifyQuantity()[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifyQuantity" duration-ms="5573" started-at="2021-10-17T13:08:15 IST" finished-at="2021-10-17T13:08:21 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message is displayed Even without valid quantity]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message is displayed Even without valid quantity
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.verifyQuantity(ProductPageValidation.java:184)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyQuantity -->
        <test-method status="PASS" signature="verifySpecification(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifySpecification" duration-ms="3399" started-at="2021-10-17T13:08:21 IST" data-provider="productnavigation" finished-at="2021-10-17T13:08:24 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[HP LP3065]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySpecification -->
        <test-method status="FAIL" signature="verifySpecification(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifySpecification" duration-ms="4273" started-at="2021-10-17T13:08:24 IST" data-provider="productnavigation" finished-at="2021-10-17T13:08:29 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[iMac]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Specification field Not Active]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Specification field Not Active
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.verifySpecification(ProductPageValidation.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySpecification -->
        <test-method status="PASS" signature="verifySpecification(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifySpecification" duration-ms="3492" started-at="2021-10-17T13:08:29 IST" data-provider="productnavigation" finished-at="2021-10-17T13:08:32 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySpecification -->
        <test-method status="FAIL" signature="verifySpecification(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifySpecification" duration-ms="3470" started-at="2021-10-17T13:08:32 IST" data-provider="productnavigation" finished-at="2021-10-17T13:08:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[MacBook Air]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Specification field Not Active]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Specification field Not Active
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.verifySpecification(ProductPageValidation.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySpecification -->
        <test-method status="FAIL" signature="verifySpecification(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifySpecification" duration-ms="4299" started-at="2021-10-17T13:08:36 IST" data-provider="productnavigation" finished-at="2021-10-17T13:08:40 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Canon EOS 5D]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Specification field Not Active]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Specification field Not Active
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.verifySpecification(ProductPageValidation.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySpecification -->
        <test-method status="FAIL" signature="verifySpecification(java.lang.String)[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="verifySpecification" duration-ms="3863" started-at="2021-10-17T13:08:40 IST" data-provider="productnavigation" finished-at="2021-10-17T13:08:44 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Samsung Galaxy Tab 10.1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Specification field Not Active]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Specification field Not Active
at org.testng.Assert.fail(Assert.java:99)
at com.plp.tests.ProductPageValidation.verifySpecification(ProductPageValidation.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySpecification -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.plp.tests.ProductPageValidation@4232c52b]" name="afterClass" is-config="true" duration-ms="1381" started-at="2021-10-17T13:08:44 IST" finished-at="2021-10-17T13:08:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.plp.tests.ProductPageValidation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
